# This file is necessary in order to run pytest.
# It allows importing the required files to be tested inside the test files.
# Example:
#   In tests/test_model.py, allows importing model.py with the line:
#     from model import get_model

[pytest]
pythonpath = .